name: Publish Lerna Modules

on:
  workflow_dispatch:
    inputs:
      modules_version:
        description: 'Lerna Modules version bump type (patch, minor, major)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Update Private variable in package.json (needed to install dependencies)
      run: |
        echo "Changing package.json 'private' field to false"
        jq '.private = true' package.json > tmpfile && mv tmpfile package.json
        
    - name: Install dependencies
      run: yarn install

      
    - name: Restore Private variable in package.json
      run: |
        echo "Changing package.json 'private' field to false"
        jq '.private = false' package.json > tmpfile && mv tmpfile package.json
    # - name: Update Lerna Modules Version in lerna.json
    #   run: |
    #     echo "Changing lerna.json 'version' field to ${{ inputs.modules_version }}"
    #     jq '.version = "${{ inputs.modules_version }}"' lerna.json > tmpfile && mv tmpfile lerna.json
              
    - name: Publish Modules to NPM
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        npx lerna run tsc && npx lerna publish ${{ inputs.modules_version }} --yes --tag-version-prefix='modules-'
        
    - name: Commit RN Version
      run: |
        git config user.email "damian.mussi@embrace.io"
        git config user.name "Mussi Damian"
        git add lerna.json
        git commit -m "bump lerna modules version to ${{ inputs.rn_version }}"
        git push origin main
