name: Publish NPM Package

on:
  workflow_dispatch:
    inputs:
      rn_version:
        description: 'RN version (e.g., 1.0.0)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: yarn install
      
    - name: Update RN Version in package.json
      run: |
        echo "Changing package.json 'version' field to ${{ inputs.package_version }}"
        jq '.version = ${{ inputs.package_version }}' package.json > tmpfile && mv tmpfile package.json
        git config user.email "damian.mussi@embrace.io"
        git config user.name "Mussi Damian"
        git add ./package.json
        git commit -m "bump rn version to ${{ inputs.package_version }}"
        git push origin main
        
    - name: Build your package (if necessary)
      run: yarn build
      
    - name: Update Private variable in package.json
      run: |
        echo "Changing package.json 'private' field to false"
        jq '.private = false' package.json > tmpfile && mv tmpfile package.json
        
    - name: Publish to NPM
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        yarn publish
